services:
  - type: web
    name: telegram-bot-webhook
    env: python
    envVars:
      - key: BOT_TOKEN
        fromSecret: telegram-bot-token
      - key: SOURCE_CHANNEL_ID
        value: "<SOURCE_CHANNEL_ID>"    # metti qui l'ID del canale di origine
      - key: DEST_CHANNEL_ID
        value: "<DEST_CHANNEL_ID>"    # metti qui l'ID del canale di destinazione
      - key: WEBHOOK_URL
        value: "<WEBHOOK_URL>"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    healthCheckPath: /
    autoDeploy: true
