services:
  - type: web
    name: rating-forward-bot
    runtime: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 7678705134:AAFo9La8QEvreETFNQjpA3ulBut0fj59e4Y
      - key: SOURCE_CHANNEL_ID
        value: -1001252470250
      - key: TARGET_CHANNEL_ID
        value: -1002801969309
